apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260626-224614-qk86p2dmi0ww-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260626-224614-qk86p2dmi0ww.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260626-224614-qk86p2dmi0ww-service
            port:
              number: 80
